

POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "email": "test@gmail.com",
    "name":"test",
    "password": "123456Aa!"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "123456Aa!"
}

###
GET http://localhost:8080/test_db